api/urls.py
# pylint: disable=C0301
# flake8: noqa: E501
from django.urls import path

from .views import (hello, huan_tshiat_huat, tshue_han_ji_e_ban_phing,
                    tshue_han_ji_e_hong_im_hu_ho, tshue_han_ji_e_peh_ue_ji,
                    tshue_han_ji_e_sip_ngoo_im, tshue_han_ji_e_tai_lo_phing_im,
                    tshue_han_ji_huat_im)

app_name = 'api'

urlpatterns = [
    # 查漢字發音
    path('tshue_han_ji_huat_im/<str:han_ji>',
         tshue_han_ji_huat_im, name='tshue_han_ji_huat_im'),
    # 查漢字十五音標音發音
    path('tshue_han_ji_huat_im/sip_ngoo_im/<str:han_ji>/',
         tshue_han_ji_e_sip_ngoo_im, name='tshue_han_ji_e_sip_ngoo_im'),
    # 查漢字台羅拼音發音
    path('tshue_han_ji_huat_im/tai_lo_phing_im/<str:han_ji>/',
         tshue_han_ji_e_tai_lo_phing_im, name='tshue_han_ji_e_tai_lo_phing_im'),
    # 查漢字白話字拼音發音
    path('tshue_han_ji_huat_im/peh_ue_ji/<str:han_ji>/',
         tshue_han_ji_e_peh_ue_ji, name='tshue_han_ji_e_peh_ue_ji'),
    # 查漢字閩拼方案發音
    path('tshue_han_ji_huat_im/ban_phing/<str:han_ji>/',
         tshue_han_ji_e_ban_phing, name='tshue_han_ji_e_ban_phing'),
    # 查漢字方音符號發音
    path('tshue_han_ji_huat_im/hong_im_hu_ho/<str:han_ji>/',
         tshue_han_ji_e_hong_im_hu_ho, name='tshue_han_ji_e_hong_im_hu_ho'),
    # 查反切法
    path('huan_tshiat_huat/', huan_tshiat_huat, name='huan_tshiat_huat'),
    # API 測試用
    path('hello/', hello, name='hello'),
]

article_pronunciation/urls.py
# article_pronunciation/urls.py
from django.urls import path

from . import views
from .views import huan_tshiat_huat

app_name = 'article_pronunciation'

urlpatterns = [
    path('save_file/', views.save_file, name='save_file'),
    path('huan_tshiat_huat/', views.huan_tshiat_huat, name='huan_tshiat_huat'),
    path('', views.index, name='index'),
]

web_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.static import serve
from web_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path(
        '',
        include(
            ('article_pronunciation.urls', 'article_pronunciation'),
            namespace='article_pronunciation',
        ),
    ),
    path(
        'han_ji_dict/',
        include(('han_ji_dict.urls', 'han_ji_dict'), namespace='han_ji_dict'),
    ),
    path('summernote/', include('django_summernote.urls')),
    # 供 summernote 上傳圖片用
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    # 供 summernote 存放靜態檔案用
    path('staic/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('logout/', LogoutView.as_view(), name='logout'),
]
# urlpatterns += staticfiles_urlpatterns()
urlpatterns = staticfiles_urlpatterns() + urlpatterns

article_pronunciation/models.py
from django.db import models
from django_summernote.fields import SummernoteTextField
from django.db.models import CharField, DateField, DateTimeField


class MyNote(models.Model):
    title: CharField = models.CharField('文章標題', max_length=200)
    author: CharField = models.CharField('作者', max_length=50, default='佚名')
    tag: CharField = models.CharField('標籤', max_length=10)
    content = SummernoteTextField('文章內容')
    publish_date: DateField = models.DateField('發佈日期', auto_now=True)
    created_at: DateTimeField = models.DateTimeField('建檔日期', auto_now_add=True)
    updated_at: DateTimeField = models.DateTimeField('更新日期', auto_now=True)

article_pronunciation/forms.py
from django import forms

pronunciation_options = {
    "tai_lo": "台羅拼音",
    "peh_oe_ji": "白話字",
    "ban_phing": "閩南語拼音方案",
    "sip_ngoo": "十五音",
    "fong_yim": "方音符號"
}

class MyForm(forms.Form):
    PRONUNCIATION_CHOICES = [
        ("tai_lo", "台羅拼音"),
        ("peh_oe_ji", "白話字"),
        ("ban_phing", "閩南語拼音方案"),
        ("sip_ngoo", "十五音"),
        ("fong_yim", "方音符號")
    ]
    pronunciation = forms.ChoiceField(choices=PRONUNCIATION_CHOICES)


class FanqieForm(forms.Form):
    characters = forms.CharField(label='反切法拼音漢字', max_length=2)

    def clean_characters(self):
        data = self.cleaned_data['characters']

        if len(data) != 2:
            raise forms.ValidationError("反切法拼音的漢字需有兩個！")

        return data

article_pronunciation/views.py
# article_pronunciation/views.py
from django.db.models import Max
from django.http import HttpResponse
from django.shortcuts import render

from han_ji_dict.models import HanJi

from .forms import FanqieForm
# from .lib_huan_tshiat_huat import parse_fanqie
from .lib_huan_tshiat_huat import parse_huan_tshiat


# 依據「漢字」查字典，並取出漢字讀音
def get_chu_im(char, pronunciation):
    # 建置「漢字」的篩選用物件
    han_ji_instances = HanJi.objects.filter(han_ji=char, freq__isnull=False).order_by(
        '-freq'
    )
    # 若漢字的篩選物件，被成功建置；則依據指定的「注音方式」，取用漢字讀音的第一個注音
    if han_ji_instances.exists():
        han_ji_instance = han_ji_instances[0]
        if pronunciation == "tai_lo":
            return han_ji_instance.get_tai_lo_chu_im()
        elif pronunciation == "peh_oe_ji":
            return han_ji_instance.get_peh_oe_ji_chu_im()
        elif pronunciation == "ban_phing":
            return han_ji_instance.get_ban_phing_chu_im()
        elif pronunciation == "sip_ngoo":
            return han_ji_instance.get_sip_ngoo_im_chu_im()
        elif pronunciation == "fong_yim":
            return han_ji_instance.get_fong_yim_fu_ho_chu_im()
    # 若漢字的薛選物件無法建立（即字典中沒有找到該漢字之注音），則返回空值字串
    return ''


# 使用者可以透過「存檔」按鈕，將標示注音的漢字存入檔案
def save_file(request):
    # 使用者在網頁上輸入漢文，並選擇注音方式，然後按下「標註注音」按鈕
    if request.method == 'POST':
        text = request.POST.get('text')
        pronunciation = request.POST.get('pronunciation')

        # 如果使用者未提供文本或發音方式，則返回
        if not text or not pronunciation:
            return HttpResponse('No text or pronunciation provided')

        # 逐字處理漢文，並標註注音
        annotated_text = []
        for char in text:
            # 若讀到換行字元，則漢字欄存放換行字元，而注音符號欄則留空白。
            if char == "\n":
                annotated_text.append(
                    {
                        'han_ji': char,
                        'chu_im_fu_ho': '',
                    }
                )
            # 若是要處理的字元為漢字，則透過查字典，取得漢字之「注音符號」
            elif char.strip():
                chu_im_fu_ho = get_chu_im(char, pronunciation)
                annotated_text.append(
                    {
                        'han_ji': char,
                        'chu_im_fu_ho': chu_im_fu_ho,
                    }
                )

        # 將注音文本轉換為字串，並存入檔案
        # 文字檔內容為一個漢字帶一段注音符號；注音符號外圍以括號：（）包住。
        output = ''.join(
            [f"{item['han_ji']}({item['chu_im_fu_ho']})" for item in annotated_text])
        with open('output.txt', 'w', encoding='utf-8') as f:
            f.write(output)
        # 顯示執行結果於返回後之網頁
        return HttpResponse('已標示注音的漢字已存檔！')
    else:
        return HttpResponse('No text or pronunciation provided')


# 使用者可以透過「標註注音」按鈕，將漢文標示注音
def index(request):
    default_text = "我可以為您標註漢字讀音"
    annotated_text = []
    pronunciation_options = {
        "sip_ngoo": "十五音",
        "fong_yim": "方音符號",
        "peh_oe_ji": "白話字",
        "tai_lo": "台羅拼音",
        "ban_phing": "閩南語拼音方案",
    }
    # 預設注音方式：台羅拼音
    selected_pronunciation = "tai_lo"

    # 使用者輸入資料
    if request.method == 'POST':
        # 取得使用者輸入的漢文
        text = request.POST.get('text')
        # 取得使用者要求的「注音／拚音」方式
        selected_pronunciation = request.POST.get('pronunciation')
        # 若使用者未挑選，則以預設：台羅拼音，為漢字標註讀音
        if not selected_pronunciation:
            selected_pronunciation = "tai_lo"

        # 標註讀音的前置處理
        if text:
            # 根據使用者的輸入（text），逐字(char) 處理
            for char in text:
                # 若是要處理的字元為「換行」，則漢字欄存放換行字元，而注音符號欄則留空白。
                if char == "\n":
                    annotated_text.append(
                        {
                            'han_ji': char,
                            'chu_im_fu_ho': '',
                        }
                    )
                elif char.strip():
                    # 若是要處理的字元為漢字，則透過查字典，取得漢字之「注音符號」
                    chu_im_fu_ho = get_chu_im(char, selected_pronunciation)
                    annotated_text.append(
                        {
                            'han_ji': char,
                            'chu_im_fu_ho': chu_im_fu_ho,
                        }
                    )
        context = {
            "default_text": default_text,
            "annotated_text": annotated_text,
            "pronunciation_options": pronunciation_options,
            "selected_pronunciation": selected_pronunciation,
        }
    else:
        # 使用者啟動功能
        context = {
            "default_text": default_text,
            "pronunciation_options": pronunciation_options,
            "selected_pronunciation": selected_pronunciation,
        }

    return render(request, "article_pronunciation/index.html", context)


def annotate_pronunciation(text):
    # annotated_text = ""
    annotated_text = []

    for character in text:
        if not character.strip():
            annotated_text.append(character)
            continue

        if character == '\n':
            annotated_text.append('<br/><br/>')
            continue

        max_freq = HanJi.objects.filter(han_ji=character).aggregate(Max('freq'))[
            'freq__max'
        ]

        if max_freq is None:
            annotated_text.append(character)
            continue

        hanji_objects = HanJi.objects.filter(han_ji=character, freq=max_freq)
        annotated_text.extend(hanji_objects)

    return annotated_text


def huan_tshiat_huat(request):
    if request.method == 'POST':
        form = FanqieForm(request.POST)
        if form.is_valid():
            characters = form.cleaned_data['characters']
            character1 = characters[0]
            character2 = characters[1]
            han_ji_haut_im = parse_huan_tshiat(character1, character2)
            return render(request,
                          'article_pronunciation/huan_tshiat_huat.html',
                          {
                              'form': form,
                              'siong_ji': character1,
                              'e_ji': character2,
                              'han_ji_haut_im': han_ji_haut_im,
                          })
    else:
        form = FanqieForm()
    return render(request,
                  'article_pronunciation/huan_tshiat_huat.html',
                  {'form': form})

article_pronunciation/templates/article_pronunciation/base.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock %}

{% block styles %}
    <!-- 加入自己的 CSS 樣式表 -->
    <link rel="stylesheet" href="{% static 'article_pronunciation/css/articles.css' %}">
{% endblock styles %}

{% block content %}
    {% block han_ji_dict_content %}
    {% endblock %}
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

{% block javascript %}
    <!-- 加入自己的 JavaScript -->
{% endblock %}

article_pronunciation/templates/article_pronunciation/huan_tshiat_huat.html
{% extends "article_pronunciation/base.html" %}
{% load static %}

{% block title %}反切法求漢字拼音{% endblock %}

{% block styles %}
<!-- 加入自己的 CSS 樣式表 -->
<link rel="stylesheet" href="{% static 'article_pronunciation/css/articles.css' %}">
{% endblock styles %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">提交</button>
    </form>
    <br/>
    {% if han_ji_haut_im %}
      <div class="content-area" style="font-size: 1.0em">
        <table>
          <tr>
            <th>反切音：</th>
            <td>{{ han_ji_haut_im.piau_im }}</td>
          </tr>
          <tr>
            <th>上&nbsp;&nbsp;&nbsp;&nbsp;字：</th>
            <td>{{ siong_ji }}({{ han_ji_haut_im.siann_bu_piau_im }})</td>
            <td>&nbsp;&nbsp;</td>
            <td>聲：</td>
            <td>{{ han_ji_haut_im.siann_piau_im }}</td>
            <td>&nbsp;&nbsp;</td>
            <td>分清濁：</td>
            <td>{{ han_ji_haut_im.tshing_lo_im}}音</td>
            <td>&nbsp;&nbsp;</td>
          </tr>
          <tr>
            <th>下&nbsp;&nbsp;&nbsp;&nbsp;字：</th>
            <td>{{ e_ji }}({{ han_ji_haut_im.un_bu_piau_im }})</td>
            <td>&nbsp;&nbsp;</td>
            <td>韻：</td>
            <td>{{ han_ji_haut_im.un_piau_im }}</td>
            <td>&nbsp;&nbsp;</td>
            <td>定四聲：</td>
            <td>{{ han_ji_haut_im.si_siann_tiau }}聲</td>
            <td>&nbsp;&nbsp;</td>
          </tr>
          <tr>
            <th></th>
            <td></td>
            <td>&nbsp;&nbsp;</td>
            <td></td>
            <td>&nbsp;&nbsp;</td>
            <td>&nbsp;&nbsp;</td>
            <td>聲&nbsp;&nbsp;調：</td>
            <td>{{ han_ji_haut_im.tiau_ho }}</td>
            <td>&nbsp;&nbsp;</td>
          </tr>
      </div>

      {% for sion_ji in han_ji_haut_sion_ji.siong_ji_sion_ji %}
          <p>{{ sion_ji }}</p>
      {% endfor %}

    {% endif %}

{% endblock content %}

{% block footer %}
{% endblock %}

{% block javascript %}
<!-- 加入自己的 JavaScript -->
{% endblock %}

article_pronunciation/templates/article_pronunciation/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} 文章標讀音 {% endblock %}

{% block styles %}
<!-- 加入自己的 CSS 樣式表 -->
<link
    rel="stylesheet"
    href="{% static 'article_pronunciation/css/articles.css' %}"
    />
{% endblock styles %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <h3><label for="text">輸入欲找讀音的漢字：</label></h3>
    <select name="pronunciation" id="pronunciation">
      {% for value, name in pronunciation_options.items %}
      <option value="{{ value }}"{% if selected_pronunciation == value %} selected{% endif %}>{{ name }}</option>
      {% endfor %}
      <!-- <option value="tai_lo">台羅拼音</option> -->
      <!-- <option value="peh_oe_ji">白話字</option> -->
      <!-- <option value="ban_phing">閩南語拼音方案</option> -->
      <!-- <option value="sip_ngoo">十五音</option> -->
      <!-- <option value="fong_yim">方音符號</option> -->
    </select>
    <br />
    <textarea name="text" id="text" rows="4" cols="80">{{ default_text }}</textarea>
    <br />
    <button type="submit">送出</button>
  </form>
  <br />
  {% if annotated_text %}
    <h3 class="content-header">已標註讀音的漢字</h3>
    <div class="content-area">
      {% for char in annotated_text %}
        {% if char.han_ji.strip == '' %}
          <br />
        {% elif char.han_ji %}
          <ruby>
            <rb>{{ char.han_ji }}</rb>
            <rp>(</rp>
            {% if selected_pronunciation == "sip_ngoo" %}
              <rt class="sip_ngoo">{{ char.chu_im_fu_ho }}</rt>
            {% elif selected_pronunciation == "fong_yim" %}
              <rt class="fong_yim">{{ char.chu_im_fu_ho }}</rt>
            {% else %}
              <rt>{{ char.chu_im_fu_ho }}</rt>
            {% endif %}
            <rp>)</rp>
          </ruby>
        {% else %}
          {{ char|safe }}
        {% endif %}
      {% endfor %}
    </div>
    <br />
    <!-- 使用者可將已注音漢字存檔 -->
    <form action="{% url 'article_pronunciation:save_file' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ default_text }}">
        <input type="hidden" name="pronunciation" value="{{ selected_pronunciation }}">
        <button type="submit">存檔</button>
    </form>
  {% endif %}
</div>
{% endblock %}

{% block javascript %}
<script>
  $(document).ready(function () {})
</script>
{% endblock javascript %}

article_pronunciation/templates/article_pronunciation/input_article.html
<!-- article_pronunciation/templates/article_pronunciation/input_article.html -->
{% extends "article_pronunciation/base.html" %}
{% load static %}

{% block title %}
  Enter Article
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
  <h2>Enter Article</h2>
  <form method="post" action="{% url 'pronunciation' %}">
    {% csrf_token %}
    <textarea name="article" rows="10" cols="50" required></textarea>
    <br>
    <button type="submit">Submit</button>
  </form>
{% endblock %}

article_pronunciation/templates/article_pronunciation/pronunciation.html
<!-- article_pronunciation/templates/article_pronunciation/pronunciation.html -->
{% extends "article_pronunciation/base.html" %}
{% load static %}

{% block title %}
  Article Pronunciation
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
  <div class="pronunciation">
    {% for item in pronunciation_list %}
      {% if item.han_ji %}
        <ruby>
          {{ item.han_ji }}<rt>{{ item.chu_im }}</rt>
        </ruby>
      {% else %}
        {{ item|safe }}
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

{% block footer %}
    <!-- {% include "footer.html" %} -->
{% endblock %}