api/urls.py
# pylint: disable=C0301
# flake8: noqa: E501
from django.urls import path

from .views import (hello, huan_tshiat_huat, tshue_han_ji_e_ban_phing,
                    tshue_han_ji_e_hong_im_hu_ho, tshue_han_ji_e_peh_ue_ji,
                    tshue_han_ji_e_sip_ngoo_im, tshue_han_ji_e_tai_lo_phing_im,
                    tshue_han_ji_huat_im)

app_name = 'api'

urlpatterns = [
    # 查漢字發音
    path('tshue_han_ji_huat_im/<str:han_ji>',
         tshue_han_ji_huat_im, name='tshue_han_ji_huat_im'),
    # 查漢字十五音標音發音
    path('tshue_han_ji_huat_im/sip_ngoo_im/<str:han_ji>/',
         tshue_han_ji_e_sip_ngoo_im, name='tshue_han_ji_e_sip_ngoo_im'),
    # 查漢字台羅拼音發音
    path('tshue_han_ji_huat_im/tai_lo_phing_im/<str:han_ji>/',
         tshue_han_ji_e_tai_lo_phing_im, name='tshue_han_ji_e_tai_lo_phing_im'),
    # 查漢字白話字拼音發音
    path('tshue_han_ji_huat_im/peh_ue_ji/<str:han_ji>/',
         tshue_han_ji_e_peh_ue_ji, name='tshue_han_ji_e_peh_ue_ji'),
    # 查漢字閩拼方案發音
    path('tshue_han_ji_huat_im/ban_phing/<str:han_ji>/',
         tshue_han_ji_e_ban_phing, name='tshue_han_ji_e_ban_phing'),
    # 查漢字方音符號發音
    path('tshue_han_ji_huat_im/hong_im_hu_ho/<str:han_ji>/',
         tshue_han_ji_e_hong_im_hu_ho, name='tshue_han_ji_e_hong_im_hu_ho'),
    # 查反切法
    path('huan_tshiat_huat/', huan_tshiat_huat, name='huan_tshiat_huat'),
    # API 測試用
    path('hello/', hello, name='hello'),
]

article_pronunciation/urls.py
# article_pronunciation/urls.py
from django.urls import path

from . import views
from .views import huan_tshiat_huat

app_name = 'article_pronunciation'

urlpatterns = [
    path('save_file/', views.save_file, name='save_file'),
    path('huan_tshiat_huat/', views.huan_tshiat_huat, name='huan_tshiat_huat'),
    path('', views.index, name='index'),
]

han_ji_dict/urls.py
from django.urls import path

from . import views

app_name = 'han_ji_dict'

urlpatterns = [
    path('', views.HanJiListView.as_view(), name='home'),
    path('<int:pk>/', views.HanJiDetailView.as_view(), name='detail'),
    path('create/', views.HanJiCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.HanJiUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.HanJiDeleteView.as_view(), name='delete'),
]

web_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.static import serve
from web_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path(
        '',
        include(
            ('article_pronunciation.urls', 'article_pronunciation'),
            namespace='article_pronunciation',
        ),
    ),
    path(
        'han_ji_dict/',
        include(('han_ji_dict.urls', 'han_ji_dict'), namespace='han_ji_dict'),
    ),
    path('summernote/', include('django_summernote.urls')),
    # 供 summernote 上傳圖片用
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    # 供 summernote 存放靜態檔案用
    path('staic/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('logout/', LogoutView.as_view(), name='logout'),
]
# urlpatterns += staticfiles_urlpatterns()
urlpatterns = staticfiles_urlpatterns() + urlpatterns

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    {% block styles %}{% endblock styles %}
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8="
        crossorigin="anonymous"></script>
</head>
<body>
    <header>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand title-brand" href="{% url 'article_pronunciation:index'  %}">
			查讀音</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'article_pronunciation:index' %}">查找讀音</a>
				</li>
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'han_ji_dict:home' %}">漢字字典</a>
				</li>
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'article_pronunciation:huan_tshiat_huat' %}">反切拼音</a>
				</li>
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'admin:index' %}">後台</a>
				</li>
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'logout' %}">登出</a>
				</li>
			</ul>
        </div>
    </nav>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
        {% block footer %}
            {% include "footer.html" %}
        {% endblock %}
    </footer>

    <script src="{% static 'js/app.js' %}"></script>

    {% block javascript %}
    <script src=""></script>

    <script>
    </script>
    {% endblock javascript %}
</body>
</html>

templates/footer.html
<p>&copy; 2023 Web App. All rights reserved.</p>