api/urls.py
# pylint: disable=C0301
# flake8: noqa: E501
from django.urls import path

from .views import (hello, huan_tshiat_huat, tshue_han_ji_e_ban_phing,
                    tshue_han_ji_e_hong_im_hu_ho, tshue_han_ji_e_peh_ue_ji,
                    tshue_han_ji_e_sip_ngoo_im, tshue_han_ji_e_tai_lo_phing_im,
                    tshue_han_ji_huat_im)

app_name = 'api'

urlpatterns = [
    # 查漢字發音
    path('tshue_han_ji_huat_im/<str:han_ji>',
         tshue_han_ji_huat_im, name='tshue_han_ji_huat_im'),
    # 查漢字十五音標音發音
    path('tshue_han_ji_huat_im/sip_ngoo_im/<str:han_ji>/',
         tshue_han_ji_e_sip_ngoo_im, name='tshue_han_ji_e_sip_ngoo_im'),
    # 查漢字台羅拼音發音
    path('tshue_han_ji_huat_im/tai_lo_phing_im/<str:han_ji>/',
         tshue_han_ji_e_tai_lo_phing_im, name='tshue_han_ji_e_tai_lo_phing_im'),
    # 查漢字白話字拼音發音
    path('tshue_han_ji_huat_im/peh_ue_ji/<str:han_ji>/',
         tshue_han_ji_e_peh_ue_ji, name='tshue_han_ji_e_peh_ue_ji'),
    # 查漢字閩拼方案發音
    path('tshue_han_ji_huat_im/ban_phing/<str:han_ji>/',
         tshue_han_ji_e_ban_phing, name='tshue_han_ji_e_ban_phing'),
    # 查漢字方音符號發音
    path('tshue_han_ji_huat_im/hong_im_hu_ho/<str:han_ji>/',
         tshue_han_ji_e_hong_im_hu_ho, name='tshue_han_ji_e_hong_im_hu_ho'),
    # 查反切法
    path('huan_tshiat_huat/', huan_tshiat_huat, name='huan_tshiat_huat'),
    # API 測試用
    path('hello/', hello, name='hello'),
]

han_ji_dict/urls.py
from django.urls import path

from . import views

app_name = 'han_ji_dict'

urlpatterns = [
    path('', views.HanJiListView.as_view(), name='home'),
    path('<int:pk>/', views.HanJiDetailView.as_view(), name='detail'),
    path('create/', views.HanJiCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.HanJiUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.HanJiDeleteView.as_view(), name='delete'),
]

web_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.static import serve
from web_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path(
        '',
        include(
            ('article_pronunciation.urls', 'article_pronunciation'),
            namespace='article_pronunciation',
        ),
    ),
    path(
        'han_ji_dict/',
        include(('han_ji_dict.urls', 'han_ji_dict'), namespace='han_ji_dict'),
    ),
    path('summernote/', include('django_summernote.urls')),
    # 供 summernote 上傳圖片用
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    # 供 summernote 存放靜態檔案用
    path('staic/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('logout/', LogoutView.as_view(), name='logout'),
]
# urlpatterns += staticfiles_urlpatterns()
urlpatterns = staticfiles_urlpatterns() + urlpatterns

han_ji_dict/models.py
import re

from django.db import models

from .ban_phing_lo_ma_ji import BanPhing
from .fong_yim_fu_ho import FongYimFuHo
from .peh_oe_ji import PehOeJi
from .sip_ngoo_im import SipNgooIm
from .tai_uan_lo_ma_ji import TaiLo


class HanJi(models.Model):
    # 漢字
    han_ji = models.CharField(max_length=2, default='')
    # 漢字讀音編碼
    chu_im = models.CharField(max_length=10, default='')
    # 讀音常用頻率
    freq = models.FloatField(default=0.0)
    # 聲母碼
    siann = models.CharField(max_length=2, default='')
    # 韻母碼
    un = models.CharField(max_length=5, default='')
    # 調號
    tiau = models.IntegerField(default=0)
    # 原編者使用的 BP 標音
    old_chu_im = models.CharField(max_length=10, null=True)
    # 十五音聲母
    sni_siann = models.CharField(max_length=10, default='')
    # 十五音韻母
    sni_un = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.han_ji

    def is_chu_im_tone(self):
        """
        判斷注音符號中是否含有「聲調」.

        若最後一個字元不是數值，表示使用者可能引用「略去聲調」不寫規則.
        """
        last_char = self.chu_im[-1]
        return last_char.isdigit()

    def split_chu_im(self):
        """
        此方法用於將「注音」(chu_im) 分解成： 聲母、韻母和調號.

        1. 使用正則表達式（regular expression）匹配聲母。這裡，聲母是由特定字
        符組成的，例如 "b", "tsh", "ts" 等。

        2. 韻母是在聲母之後、調號之前的部分。為了找到韻母，我們首先計算聲母的
        長度（len(siann_bu)），然後從音節的開頭去掉聲母部分，並在音節的末尾
        去掉調號部分。

        3. 調號是音節最後一個字符。

        4. 調號可省略規則：
           當「韻母」為「舒聲韻」時，若「聲調」未標示，則代表「第一聲」；
           當「韻母」為「入聲韻」時，若「聲調」未標示，則代表「第四聲」。
        """

        valid_un_bu_endings = [
            'un', 'ian', 'im', 'ui', 'ee', 'an', 'ong', 'uai', 'ing', 'uan',
            'oo', 'iau', 'ei', 'iong', 'o', 'ai', 'in', 'iang', 'am', 'ua',
            'ang', 'iam', 'au', 'ia', 'ue', 'ann', 'u', 'a', 'i', 'iu', 'enn',
            'uinn', 'io', 'inn', 'ionn', 'iannh', 'uann', 'ng', 'e', 'ainn',
            'onn', 'm', 'uang', 'uainn', 'uenn', 'iaunn', 'om', 'aunn', 'onn',
            'iunn'
        ]

        result = []

        # 正規表達式，用於表達所有可能的聲母。
        siann_pattern = re.compile(r"(b|tsh|ts|g|h|j|kh|k|l|m|ng|n|ph|p|s|th|t|q)?")
        # 透過 match 方法，找到「注音」之中的「聲母」。然後再利用 group
        # 方法，將注音群分「聲母」與「韻母」。
        siann_match = siann_pattern.match(self.chu_im)

        if siann_match:
            siann_bu = siann_match.group()
        else:
            siann_bu = ""

        # 依據「注音符號」中是否有含「聲調」，決定取得韻母與調號的方式。
        if self.is_chu_im_tone():
            # 若注音符號最後一個字元為「數值」，表「聲調」。即
            un_bu = self.chu_im[len(siann_bu): -1]
            tiau = self.chu_im[-1]
        else:
            un_bu = self.chu_im[len(siann_bu):]
            if un_bu in valid_un_bu_endings:
                tiau = '1'
            else:
                tiau = '4'

        result += [siann_bu]
        result += [un_bu]
        result += [tiau]
        return result

    # ==========================================================
    # 取得十五音的注音
    # ==========================================================
    def get_sip_ngoo_im_chu_im(self):
        # 取得「聲母」
        siann = self.split_chu_im()[0]
        # 取得「韻母」
        un = self.split_chu_im()[1]
        # 取得「調號」
        tiau = self.split_chu_im()[2]

        sip_ngoo_im = SipNgooIm()
        return sip_ngoo_im.get_chu_im(siann, un, tiau)

    # ==========================================================
    # 取得台羅拼音（TL）的注音
    # ==========================================================
    def get_tai_lo_chu_im(self):
        # 取得「聲母」
        siann = self.split_chu_im()[0]
        # 取得「韻母」
        un = self.split_chu_im()[1]
        # 取得「調號」
        tiau = self.split_chu_im()[2]

        chu_im_method = TaiLo()
        return chu_im_method.get_chu_im(siann, un, tiau)

    # ==========================================================
    # 取得白話字（POJ）的注音
    # ==========================================================
    def get_peh_oe_ji_chu_im(self):
        # 取得「聲母」
        siann = self.split_chu_im()[0]
        # 取得「韻母」
        un = self.split_chu_im()[1]
        # 取得「調號」
        tiau = self.split_chu_im()[2]

        chu_im_method = PehOeJi()
        return chu_im_method.get_chu_im(siann, un, tiau)

    # ==========================================================
    # 取得閩南語拼音方案（BP）注音
    # ==========================================================
    def get_ban_phing_chu_im(self):
        # 取得「聲母」
        siann = self.split_chu_im()[0]
        # 取得「韻母」
        un = self.split_chu_im()[1]
        # 取得「調號」
        tiau = self.split_chu_im()[2]

        chu_im_method = BanPhing()
        return chu_im_method.get_chu_im(siann, un, tiau)

    # ==========================================================
    # 取得方音符號（TPS）注音
    # ==========================================================
    def get_fong_yim_fu_ho_chu_im(self):
        # 取得「聲母」
        siann = self.split_chu_im()[0]
        # 取得「韻母」
        un = self.split_chu_im()[1]
        # 取得「調號」
        tiau = self.split_chu_im()[2]

        chu_im_method = FongYimFuHo()
        return chu_im_method.get_chu_im(siann, un, tiau)

han_ji_dict/forms.py
from django.forms import ModelForm

from .models import HanJi


class HanJiForm(ModelForm):
    class Meta:
        model = HanJi
        fields = '__all__'
        labels = {
            'han_ji': '漢字',
            'chu_im': '讀音編碼',
            'freq': '讀音常用頻率',
            'siann': '聲母碼',
            'un': '韻母碼',
            'tiau': '調號',
            'old_chu_im': '原編者使用的 BP 標音',
            'sni_siann': '十五音聲母',
            'sni_un': '十五音韻母',
        }

    def __init__(self, *args, **kwargs):
        """定義以下欄位可略過."""
        super().__init__(*args, **kwargs)
        self.fields['siann'].required = False
        self.fields['old_chu_im'].required = False
        self.fields['sni_siann'].required = False
        self.fields['sni_un'].required = False

han_ji_dict/views.py
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .forms import HanJiForm
from .models import HanJi


class HanJiListView(ListView):
    model = HanJi
    template_name = 'han_ji_dict/index.html'
    paginate_by = 8


class HanJiDetailView(DetailView):
    model = HanJi
    template_name = 'han_ji_dict/detail.html'
    success_url = reverse_lazy('han_ji_dict:home')


class HanJiCreateView(CreateView):
    model = HanJi
    form_class = HanJiForm
    template_name = 'han_ji_dict/create.html'
    success_url = reverse_lazy('han_ji_dict:home')


class HanJiUpdateView(UpdateView):
    model = HanJi
    form_class = HanJiForm
    template_name = 'han_ji_dict/update.html'
    success_url = reverse_lazy('han_ji_dict:home')


class HanJiDeleteView(DeleteView):
    model = HanJi
    template_name = 'han_ji_dict/delete.html'
    success_url = reverse_lazy('han_ji_dict:home')

# class HanJiSearchView(ListView):
#     model = HanJi
#     template_name = 'han_ji_dict/search.html'
#     paginate_by = 8
#
#     def get_queryset(self):
#         query = self.request.GET.get('q')
#         object_list = HanJi.objects.filter(hanji__contains=query)
#         return object_list

han_ji_dict/templates/han_ji_dict/base.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'han_ji_dict/css/han_ji_dict.css' %}">
{% endblock styles %}

{% block content %}
    {% block han_ji_dict_content %}
    {% endblock %}
{% endblock %}

han_ji_dict/templates/han_ji_dict/create.html
{% extends "han_ji_dict/base.html" %}

{% block title %}
新增漢字及其音標
{% endblock %}

{% block han_ji_dict_content %}
<h1>新增漢字及其音標</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">新增漢字</button>
  <!-- 回 App 主頁 -->
  <a href="{% url 'han_ji_dict:home' %}" class="btn btn-danger">回主頁</a>
</form>
{% endblock %}

han_ji_dict/templates/han_ji_dict/delete.html
{% extends "han_ji_dict/base.html" %}

{% block title %}
刪漢字
{% endblock %}

{% block han_ji_dict_content %}
<h1>確認要刪此漢字嗎？？？</h1>
<p>漢字: {{ object.han_ji }}</p>
<p>讀音編碼: {{ object.chu_im }}</p>
<p>聲母碼: {{ object.siann }}</p>
<p>韻母碼: {{ object.un }}</p>
<p>調號: {{ object.tiau }}</p>
<!-- 其他漢字屬性，如所需 -->

<!-- 回 App 主頁 -->
<a href="{% url 'han_ji_dict:home' %}" class="btn btn-success">回主頁</a>

<!-- 刪除按鈕 -->
<form action="{% url 'han_ji_dict:delete' object.pk %}" method="post" style="display:inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">刪除</button>
</form>
{% endblock %}

han_ji_dict/templates/han_ji_dict/detail.html
{% extends "han_ji_dict/base.html" %}

{% block title %}
顯示漢字音標明細
{% endblock %}

{% block han_ji_dict_content %}
<h1>漢字音標明細</h1>
<p>漢字: {{ object.han_ji }}</p>
<p>讀音編碼: {{ object.chu_im }}</p>
<p>聲母碼: {{ object.siann }}</p>
<p>韻母碼: {{ object.un }}</p>
<p>調號: {{ object.tiau }}</p>
<!-- 其他漢字屬性，如所需 -->

<!-- 回 App 主頁 -->
<a href="{% url 'han_ji_dict:home' %}" class="btn btn-success">回主頁</a>

<!-- 更新按鈕 -->
<a href="{% url 'han_ji_dict:update' object.pk %}" class="btn btn-primary">更新</a>

<!-- 刪除按鈕 -->
<a href="{% url 'han_ji_dict:delete' object.pk %}" class="btn btn-danger">刪除</a>
{% endblock %}

han_ji_dict/templates/han_ji_dict/index.html
{% extends "han_ji_dict/base.html" %}

{% load mathfilters %}

{% block title %}
漢字典首頁
{% endblock %}

{% block han_ji_dict_content %}
<div class="text-center">
    <h4>漢字字典</h4>
    <a href="{% url 'han_ji_dict:create' %}" class="btn btn-success"
       style="font-size: 70%;">
        新增漢字
    </a>
</div>
<br>
<table class="table table-bordered">
    <thead style="font-size: 10px; color: darkblue; background-color: lightgrey;">
        <tr>
            <th>序號</th>
            <th>漢字</th>
            <th>讀音編碼</th>
            <th>台羅拼音</th>
            <th>白話字</th>
            <th>閩拼方案</th>
            <th>雅俗通15音</th>
            <th>方音符號</th>
            <th>聲母碼</th>
            <th>韻母碼</th>
            <th>調&nbsp;&nbsp;號</th>
            <th>常用頻率</th>
        </tr>
    </thead>
    <tbody>
        {% for han_ji in object_list %}
        <tr>
            {% with page_offset=page_obj.number|add:-1|mul:page_obj.paginator.per_page %}
                <td>{{ forloop.counter|add:page_offset }}</td>
            {% endwith %}
            <td>
                <a href="{% url 'han_ji_dict:detail' han_ji.pk %}">{{ han_ji.han_ji }}</a>
            </td>
            <td>{{ han_ji.chu_im }}</td>
            <td>{{ han_ji.get_tai_lo_chu_im }}</td>
            <td>{{ han_ji.get_peh_oe_ji_chu_im }}</td>
            <td>{{ han_ji.get_ban_phing_chu_im }}</td>
            <td>{{ han_ji.get_sip_ngoo_im_chu_im }}</td>
            <td>{{ han_ji.get_fong_yim_fu_ho_chu_im }}</td>
            <td>{{ han_ji.siann }}</td>
            <td>{{ han_ji.un }}</td>
            <td>{{ han_ji.tiau }}</td>
            <td>{{ han_ji.freq }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "pagination.html" with page=page_obj %}


{% endblock %}

han_ji_dict/templates/han_ji_dict/update.html
{% extends "han_ji_dict/base.html" %}

{% block title %}
編輯漢字音標明細
{% endblock %}

{% block han_ji_dict_content %}
<h1>編輯漢字音標明細</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">保存更改</button>
  <!-- 回 App 主頁 -->
  <a href="{% url 'han_ji_dict:home' %}" class="btn btn-danger">回主頁</a>
</form>
{% endblock %}